// Code generated by yolo gen. DO NOT EDIT.
package task

import (
	"time"

	"github.com/yolo-hq/yolo/core/entity"
)

// Task is a generated entity struct from Blueprint spec.
type Task struct {
	entity.BaseEntity `bun:",extend"`

	AcceptanceCriteria string     `bun:"acceptance_criteria,notnull" json:"acceptance_criteria"`
	Branch             string     `bun:"branch,notnull" json:"branch"`
	CommitHash         string     `bun:"commit_hash" json:"commit_hash"`
	CompletedAt        *time.Time `bun:"completed_at" json:"completed_at"`
	CostUsd            float64    `bun:"cost_usd,default:0" json:"cost_usd"`
	DependsOn          any        `bun:"depends_on,default:'[]'" json:"depends_on"`
	MaxRetries         int        `bun:"max_retries,default:3" json:"max_retries"`
	Model              string     `bun:"model,default:''" json:"model"`
	PRDID              string     `bun:"prd_id,notnull" json:"prd_id"`
	ProjectID          string     `bun:"project_id,notnull" json:"project_id"`
	RunCount           int        `bun:"run_count,default:0" json:"run_count"`
	Sequence           int        `bun:"sequence,notnull" json:"sequence"`
	Spec               string     `bun:"spec,notnull" json:"spec"`
	StartedAt          *time.Time `bun:"started_at" json:"started_at"`
	Status             string     `bun:"status,default:'queued'" json:"status"`
	Summary            string     `bun:"summary" json:"summary"`
	Title              string     `bun:"title,notnull" json:"title"`
}
