// Code generated by yolo gen. DO NOT EDIT.
package task

import (
	"context"

	"github.com/yolo-hq/yolo/core/service"
)

// TaskCancelledEvent is the append-only fact emitted for TaskCancelled.
type TaskCancelledEvent struct {
	ActorID string `json:"actor_id"`
	TaskID  string `json:"task_id"`
}

// EmitTaskCancelled builds a TaskCancelledEvent and records it on the ctx-scoped
// service event collector.
func EmitTaskCancelled(ctx context.Context, actorID string, taskID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "task_cancelled",
		Data: TaskCancelledEvent{
			ActorID: actorID,
			TaskID:  taskID,
		},
	})
}

// TaskCompletedEvent is the append-only fact emitted for TaskCompleted.
type TaskCompletedEvent struct {
	ActorID string `json:"actor_id"`
	TaskID  string `json:"task_id"`
}

// EmitTaskCompleted builds a TaskCompletedEvent and records it on the ctx-scoped
// service event collector.
func EmitTaskCompleted(ctx context.Context, actorID string, taskID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "task_completed",
		Data: TaskCompletedEvent{
			ActorID: actorID,
			TaskID:  taskID,
		},
	})
}

// TaskFailedEvent is the append-only fact emitted for TaskFailed.
type TaskFailedEvent struct {
	Reason string `json:"reason"`
	TaskID string `json:"task_id"`
}

// EmitTaskFailed builds a TaskFailedEvent and records it on the ctx-scoped
// service event collector.
func EmitTaskFailed(ctx context.Context, reason string, taskID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "task_failed",
		Data: TaskFailedEvent{
			Reason: reason,
			TaskID: taskID,
		},
	})
}

// TaskStartedEvent is the append-only fact emitted for TaskStarted.
type TaskStartedEvent struct {
	RunID  string `json:"run_id"`
	TaskID string `json:"task_id"`
}

// EmitTaskStarted builds a TaskStartedEvent and records it on the ctx-scoped
// service event collector.
func EmitTaskStarted(ctx context.Context, runID string, taskID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "task_started",
		Data: TaskStartedEvent{
			RunID:  runID,
			TaskID: taskID,
		},
	})
}
