// Code generated by yolo gen. DO NOT EDIT.
package task

import (
	"github.com/yolo-hq/yolo/core/filter"
)

// TaskFilter declares the list filters supported for the Task entity.
// Each field is a typed pointer to a core/filter field type; non-nil
// fields are auto-applied to the SQL builder via filter.ApplyStruct.
type TaskFilter struct {
	filter.Base

	Branch    *filter.StringField `json:"branch" filter:"branch"`
	PrdID     *filter.IDField     `json:"prd_id" filter:"prd_id"`
	ProjectID *filter.IDField     `json:"project_id" filter:"project_id"`
	Status    *filter.StringField `json:"status" filter:"status"`
}
