// Code generated by yolo gen. DO NOT EDIT.
package task

import (
	"github.com/yolo-hq/yolo/core/action"

	"github.com/yolo-hq/app-yolo-factory/.yolo/fields"
)

// Task is the state machine for the Task entity.
var Task = action.StateMachine{
	Entity: "Task",
	Field:  fields.Task.Status,
	Transitions: action.Transitions{
		"Block":    {From: []string{"running"}, To: "blocked"},
		"Cancel":   {From: []string{"queued", "running", "blocked"}, To: "cancelled"},
		"Complete": {From: []string{"reviewing"}, To: "done"},
		"Fail":     {From: []string{"running", "reviewing"}, To: "failed"},
		"Review":   {From: []string{"running"}, To: "reviewing"},
		"Start":    {From: []string{"queued"}, To: "running"},
		"Unblock":  {From: []string{"blocked"}, To: "queued"},
	},
}
