// Code generated by yolo serve. DO NOT EDIT.
package main

import (
	"github.com/yolo-hq/yolo"

	_ "github.com/yolo-hq/app-yolo-factory/apps/common/factory/actions"
	_ "github.com/yolo-hq/app-yolo-factory/apps/common/factory/entities"
	_ "github.com/yolo-hq/app-yolo-factory/apps/common/factory/filters"
	_ "github.com/yolo-hq/app-yolo-factory/apps/common/factory/inputs"
	"github.com/uptrace/bun"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/actions"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/commands"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/entities"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/filters"
	"github.com/yolo-hq/yolo/core/command"
	"github.com/yolo-hq/yolo/core/jobs"
	"github.com/yolo-hq/yolo/core/registry"
	bunrepo "github.com/yolo-hq/yolo/core/bun"
	domjobs "github.com/yolo-hq/app-yolo-factory/apps/common/factory/jobs"
)

func main() {
	// Entities
	registry.Register(
		entities.Insight{},
		entities.LintResult{},
		entities.PRD{},
		entities.Project{},
		entities.Question{},
		entities.Review{},
		entities.Run{},
		entities.Step{},
		entities.Suggestion{},
		entities.Task{},
	)

	// Repositories
	registry.RegisterRepoFactory("Insight", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Insight](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Insight](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("LintResult", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.LintResult](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.LintResult](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("PRD", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.PRD](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.PRD](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Project", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Project](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Project](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Question", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Question](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Question](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Review", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Review](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Review](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Run", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Run](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Run](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Step", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Step](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Step](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Suggestion", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Suggestion](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Suggestion](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Task", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Task](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Task](db.(*bun.DB))
	})

	// Actions
	registry.RegisterActions("Insight",
		&actions.AcknowledgeInsightAction{},
		&actions.ApplyInsightAction{},
		&actions.DismissInsightAction{},
	)
	registry.RegisterActions("PRD",
		&actions.ApprovePRDAction{},
		&actions.ExecutePRDAction{},
		&actions.SubmitPRDAction{},
	)
	registry.RegisterActions("Project",
		&actions.CreateProjectAction{},
		&actions.PauseProjectAction{},
		&actions.ResumeProjectAction{},
		&actions.UpdateProjectAction{},
	)
	registry.RegisterActions("Question",
		&actions.AnswerQuestionAction{},
	)
	registry.RegisterActions("Run",
		&actions.CompleteRunAction{},
	)
	registry.RegisterActions("Suggestion",
		&actions.ApproveSuggestionAction{},
		&actions.RejectSuggestionAction{},
	)
	registry.RegisterActions("Task",
		&actions.CancelTaskAction{},
		&actions.RetryTaskAction{},
	)

	// Filters
	registry.RegisterFilter("Insight", &filters.InsightFilter{})
	registry.RegisterFilter("LintResult", &filters.LintResultFilter{})
	registry.RegisterFilter("PRD", &filters.PRDFilter{})
	registry.RegisterFilter("Project", &filters.ProjectFilter{})
	registry.RegisterFilter("Question", &filters.QuestionFilter{})
	registry.RegisterFilter("Review", &filters.ReviewFilter{})
	registry.RegisterFilter("Run", &filters.RunFilter{})
	registry.RegisterFilter("Step", &filters.StepFilter{})
	registry.RegisterFilter("Suggestion", &filters.SuggestionFilter{})
	registry.RegisterFilter("Task", &filters.TaskFilter{})

	// Jobs
	jobs.RegisterHandler(&domjobs.AdvisorJob{})
	jobs.RegisterHandler(&domjobs.BackupSnapshotJob{})
	jobs.RegisterHandler(&domjobs.CheckTimeoutsJob{})
	jobs.RegisterHandler(&domjobs.ExecuteWorkflowJob{})
	jobs.RegisterHandler(&domjobs.PlanPRDJob{})
	jobs.RegisterHandler(&domjobs.ProcessAdvisorJob{})
	jobs.RegisterHandler(&domjobs.ResetBudgetsJob{})
	jobs.RegisterHandler(&domjobs.SentinelJob{})

	// Commands
	command.Register(&commands.AdvisorRun{})
	command.Register(&commands.Backup{})
	command.Register(&commands.Cost{})
	command.Register(&commands.InsightAcknowledge{})
	command.Register(&commands.InsightApply{})
	command.Register(&commands.InsightDismiss{})
	command.Register(&commands.InsightList{})
	command.Register(&commands.PRDApprove{})
	command.Register(&commands.PRDDiff{})
	command.Register(&commands.PRDExecute{})
	command.Register(&commands.PRDGet{})
	command.Register(&commands.PRDList{})
	command.Register(&commands.PRDSubmit{})
	command.Register(&commands.ProjectAdd{})
	command.Register(&commands.ProjectArchive{})
	command.Register(&commands.ProjectGet{})
	command.Register(&commands.ProjectList{})
	command.Register(&commands.ProjectPause{})
	command.Register(&commands.ProjectResume{})
	command.Register(&commands.ProjectScan{})
	command.Register(&commands.ProjectUpdate{})
	command.Register(&commands.QuestionAnswer{})
	command.Register(&commands.QuestionList{})
	command.Register(&commands.Recover{})
	command.Register(&commands.SentinelRun{})
	command.Register(&commands.Status{})
	command.Register(&commands.SuggestionApprove{})
	command.Register(&commands.SuggestionList{})
	command.Register(&commands.SuggestionReject{})
	command.Register(&commands.TaskCancel{})
	command.Register(&commands.TaskGet{})
	command.Register(&commands.TaskList{})
	command.Register(&commands.TaskRetry{})

	yolo.MustServe("./app.yml")
}
