// Code generated by yolo serve. DO NOT EDIT.
package main

import (
	"github.com/yolo-hq/yolo"

	_ "github.com/yolo-hq/app-yolo-factory/apps/common/factory/actions"
	_ "github.com/yolo-hq/app-yolo-factory/apps/common/factory/entities"
	_ "github.com/yolo-hq/app-yolo-factory/apps/common/factory/filters"
	_ "github.com/yolo-hq/app-yolo-factory/apps/common/factory/inputs"
	"github.com/uptrace/bun"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/actions"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/commands"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/entities"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/filters"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/services"
	"github.com/yolo-hq/yolo/core/command"
	"github.com/yolo-hq/yolo/core/jobs"
	"github.com/yolo-hq/yolo/core/registry"
	bunrepo "github.com/yolo-hq/yolo/core/bun"
	domjobs "github.com/yolo-hq/app-yolo-factory/apps/common/factory/jobs"
)

func main() {
	// Wirable instances
	var (
		svcAdvisorService = &services.AdvisorService{}
		svcBackupService = &services.BackupService{}
		svcContextService = &services.ContextService{}
		svcDependencyService = &services.DependencyService{}
		svcGitService = &services.GitService{}
		svcIntegrationReviewService = &services.IntegrationReviewService{}
		svcLinterService = &services.LinterService{}
		svcOrchestratorService = &services.OrchestratorService{}
		svcPlannerService = &services.PlannerService{}
		svcProcessAdvisorService = &services.ProcessAdvisorService{}
		svcSentinelService = &services.SentinelService{}
		actApprovePRDAction = &actions.ApprovePRDAction{}
		actCompleteRunAction = &actions.CompleteRunAction{}
		actExecutePRDAction = &actions.ExecutePRDAction{}
		jobAdvisorJob = &domjobs.AdvisorJob{}
		jobBackupSnapshotJob = &domjobs.BackupSnapshotJob{}
		jobCheckTimeoutsJob = &domjobs.CheckTimeoutsJob{}
		jobExecuteWorkflowJob = &domjobs.ExecuteWorkflowJob{}
		jobPlanPRDJob = &domjobs.PlanPRDJob{}
		jobProcessAdvisorJob = &domjobs.ProcessAdvisorJob{}
		jobResetBudgetsJob = &domjobs.ResetBudgetsJob{}
		jobSentinelJob = &domjobs.SentinelJob{}
	)

	// Entities
	registry.Register(
		entities.Insight{},
		entities.LintResult{},
		entities.PRD{},
		entities.Project{},
		entities.Question{},
		entities.Review{},
		entities.Run{},
		entities.Step{},
		entities.Suggestion{},
		entities.Task{},
	)

	// Repositories
	registry.RegisterRepoFactory("Insight", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Insight](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Insight](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("LintResult", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.LintResult](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.LintResult](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("PRD", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.PRD](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.PRD](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Project", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Project](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Project](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Question", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Question](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Question](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Review", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Review](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Review](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Run", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Run](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Run](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Step", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Step](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Step](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Suggestion", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Suggestion](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Suggestion](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Task", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Task](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Task](db.(*bun.DB))
	})

	// Actions
	registry.RegisterActions("Insight",
		&actions.AcknowledgeInsightAction{},
		&actions.ApplyInsightAction{},
		&actions.DismissInsightAction{},
	)
	registry.RegisterActions("PRD",
		actApprovePRDAction,
		actExecutePRDAction,
		&actions.SubmitPRDAction{},
	)
	registry.RegisterActions("Project",
		&actions.CreateProjectAction{},
		&actions.PauseProjectAction{},
		&actions.ResumeProjectAction{},
		&actions.UpdateProjectAction{},
	)
	registry.RegisterActions("Question",
		&actions.AnswerQuestionAction{},
	)
	registry.RegisterActions("Run",
		actCompleteRunAction,
	)
	registry.RegisterActions("Suggestion",
		&actions.ApproveSuggestionAction{},
		&actions.RejectSuggestionAction{},
	)
	registry.RegisterActions("Task",
		&actions.CancelTaskAction{},
		&actions.RetryTaskAction{},
	)

	// Filters
	registry.RegisterFilter("Insight", &filters.InsightFilter{})
	registry.RegisterFilter("LintResult", &filters.LintResultFilter{})
	registry.RegisterFilter("PRD", &filters.PRDFilter{})
	registry.RegisterFilter("Project", &filters.ProjectFilter{})
	registry.RegisterFilter("Question", &filters.QuestionFilter{})
	registry.RegisterFilter("Review", &filters.ReviewFilter{})
	registry.RegisterFilter("Run", &filters.RunFilter{})
	registry.RegisterFilter("Step", &filters.StepFilter{})
	registry.RegisterFilter("Suggestion", &filters.SuggestionFilter{})
	registry.RegisterFilter("Task", &filters.TaskFilter{})

	// Jobs
	jobs.RegisterHandler(jobAdvisorJob)
	jobs.RegisterHandler(jobBackupSnapshotJob)
	jobs.RegisterHandler(jobCheckTimeoutsJob)
	jobs.RegisterHandler(jobExecuteWorkflowJob)
	jobs.RegisterHandler(jobPlanPRDJob)
	jobs.RegisterHandler(jobProcessAdvisorJob)
	jobs.RegisterHandler(jobResetBudgetsJob)
	jobs.RegisterHandler(jobSentinelJob)

	// Commands
	command.Register(&commands.AdvisorRun{})
	command.Register(&commands.Backup{})
	command.Register(&commands.Cost{})
	command.Register(&commands.InsightAcknowledge{})
	command.Register(&commands.InsightApply{})
	command.Register(&commands.InsightDismiss{})
	command.Register(&commands.InsightList{})
	command.Register(&commands.PRDApprove{})
	command.Register(&commands.PRDDiff{})
	command.Register(&commands.PRDExecute{})
	command.Register(&commands.PRDGet{})
	command.Register(&commands.PRDList{})
	command.Register(&commands.PRDSubmit{})
	command.Register(&commands.ProjectAdd{})
	command.Register(&commands.ProjectArchive{})
	command.Register(&commands.ProjectGet{})
	command.Register(&commands.ProjectList{})
	command.Register(&commands.ProjectPause{})
	command.Register(&commands.ProjectResume{})
	command.Register(&commands.ProjectScan{})
	command.Register(&commands.ProjectUpdate{})
	command.Register(&commands.QuestionAnswer{})
	command.Register(&commands.QuestionList{})
	command.Register(&commands.Recover{})
	command.Register(&commands.SentinelRun{})
	command.Register(&commands.Status{})
	command.Register(&commands.SuggestionApprove{})
	command.Register(&commands.SuggestionList{})
	command.Register(&commands.SuggestionReject{})
	command.Register(&commands.TaskCancel{})
	command.Register(&commands.TaskGet{})
	command.Register(&commands.TaskList{})
	command.Register(&commands.TaskRetry{})

	// Dependency injection — runs after DB is initialized
	registry.RegisterWireFunc(func(db any, repos map[string]*registry.RepoSet) {
		bunDB := db.(*bun.DB)
		_ = bunDB
		// TODO: wire svcAdvisorService.Claude (*claude.Client) — requires config
		svcAdvisorService.Context = svcContextService
		svcDependencyService.TaskRead = bunrepo.NewReadRepository[entities.Task](db.(*bun.DB))
		svcDependencyService.TaskWrite = bunrepo.NewWriteRepository[entities.Task](db.(*bun.DB))
		// TODO: wire svcIntegrationReviewService.Claude (*claude.Client) — requires config
		svcIntegrationReviewService.Context = svcContextService
		// TODO: wire svcOrchestratorService.Claude (*claude.Client) — requires config
		svcOrchestratorService.Git = svcGitService
		svcOrchestratorService.Context = svcContextService
		svcOrchestratorService.Dependency = svcDependencyService
		svcOrchestratorService.Linter = svcLinterService
		// TODO: wire svcPlannerService.Claude (*claude.Client) — requires config
		svcPlannerService.Context = svcContextService
		svcPlannerService.Dependency = svcDependencyService
		// TODO: wire svcProcessAdvisorService.Claude (*claude.Client) — requires config
		// TODO: wire .Claude (*claude.Client) — requires config
		// TODO: wire svcSentinelService.Claude (*claude.Client) — requires config
		actApprovePRDAction.JobClient = jobs.GlobalClient()
		actApprovePRDAction.PlanPRDJob = jobPlanPRDJob
		actCompleteRunAction.JobClient = jobs.GlobalClient()
		actCompleteRunAction.WorkflowJob = jobExecuteWorkflowJob
		actExecutePRDAction.JobClient = jobs.GlobalClient()
		actExecutePRDAction.PlanJob = jobPlanPRDJob
		jobAdvisorJob.Advisor = svcAdvisorService
		jobAdvisorJob.ProjectRead = bunrepo.NewReadRepository[entities.Project](db.(*bun.DB))
		jobAdvisorJob.TaskRead = bunrepo.NewReadRepository[entities.Task](db.(*bun.DB))
		jobAdvisorJob.RunRead = bunrepo.NewReadRepository[entities.Run](db.(*bun.DB))
		jobAdvisorJob.SuggestionWrite = bunrepo.NewWriteRepository[entities.Suggestion](db.(*bun.DB))
		jobBackupSnapshotJob.Backup = svcBackupService
		jobBackupSnapshotJob.ProjectRead = bunrepo.NewReadRepository[entities.Project](db.(*bun.DB))
		jobBackupSnapshotJob.PRDRead = bunrepo.NewReadRepository[entities.PRD](db.(*bun.DB))
		jobBackupSnapshotJob.TaskRead = bunrepo.NewReadRepository[entities.Task](db.(*bun.DB))
		jobBackupSnapshotJob.QuestionRead = bunrepo.NewReadRepository[entities.Question](db.(*bun.DB))
		jobBackupSnapshotJob.SuggestionRead = bunrepo.NewReadRepository[entities.Suggestion](db.(*bun.DB))
		jobCheckTimeoutsJob.RunRead = bunrepo.NewReadRepository[entities.Run](db.(*bun.DB))
		jobCheckTimeoutsJob.RunWrite = bunrepo.NewWriteRepository[entities.Run](db.(*bun.DB))
		jobCheckTimeoutsJob.TaskRead = bunrepo.NewReadRepository[entities.Task](db.(*bun.DB))
		jobCheckTimeoutsJob.TaskWrite = bunrepo.NewWriteRepository[entities.Task](db.(*bun.DB))
		jobCheckTimeoutsJob.ProjectRead = bunrepo.NewReadRepository[entities.Project](db.(*bun.DB))
		jobExecuteWorkflowJob.Orchestrator = svcOrchestratorService
		jobExecuteWorkflowJob.TaskRead = bunrepo.NewReadRepository[entities.Task](db.(*bun.DB))
		jobExecuteWorkflowJob.TaskWrite = bunrepo.NewWriteRepository[entities.Task](db.(*bun.DB))
		jobExecuteWorkflowJob.RunWrite = bunrepo.NewWriteRepository[entities.Run](db.(*bun.DB))
		jobExecuteWorkflowJob.StepWrite = bunrepo.NewWriteRepository[entities.Step](db.(*bun.DB))
		jobExecuteWorkflowJob.ReviewWrite = bunrepo.NewWriteRepository[entities.Review](db.(*bun.DB))
		jobExecuteWorkflowJob.PRDRead = bunrepo.NewReadRepository[entities.PRD](db.(*bun.DB))
		jobExecuteWorkflowJob.ProjectRead = bunrepo.NewReadRepository[entities.Project](db.(*bun.DB))
		jobPlanPRDJob.Planner = svcPlannerService
		jobPlanPRDJob.PRDRead = bunrepo.NewReadRepository[entities.PRD](db.(*bun.DB))
		jobPlanPRDJob.PRDWrite = bunrepo.NewWriteRepository[entities.PRD](db.(*bun.DB))
		jobPlanPRDJob.TaskWrite = bunrepo.NewWriteRepository[entities.Task](db.(*bun.DB))
		jobPlanPRDJob.ProjectRead = bunrepo.NewReadRepository[entities.Project](db.(*bun.DB))
		jobProcessAdvisorJob.Advisor = svcProcessAdvisorService
		jobProcessAdvisorJob.ProjectRead = bunrepo.NewReadRepository[entities.Project](db.(*bun.DB))
		jobProcessAdvisorJob.TaskRead = bunrepo.NewReadRepository[entities.Task](db.(*bun.DB))
		jobProcessAdvisorJob.RunRead = bunrepo.NewReadRepository[entities.Run](db.(*bun.DB))
		jobProcessAdvisorJob.StepRead = bunrepo.NewReadRepository[entities.Step](db.(*bun.DB))
		jobProcessAdvisorJob.ReviewRead = bunrepo.NewReadRepository[entities.Review](db.(*bun.DB))
		jobProcessAdvisorJob.LintResultRead = bunrepo.NewReadRepository[entities.LintResult](db.(*bun.DB))
		jobProcessAdvisorJob.InsightWrite = bunrepo.NewWriteRepository[entities.Insight](db.(*bun.DB))
		jobResetBudgetsJob.ProjectRead = bunrepo.NewReadRepository[entities.Project](db.(*bun.DB))
		jobResetBudgetsJob.ProjectWrite = bunrepo.NewWriteRepository[entities.Project](db.(*bun.DB))
		jobSentinelJob.Sentinel = svcSentinelService
		jobSentinelJob.ProjectRead = bunrepo.NewReadRepository[entities.Project](db.(*bun.DB))
		jobSentinelJob.TaskWrite = bunrepo.NewWriteRepository[entities.Task](db.(*bun.DB))
		jobSentinelJob.SuggestionWrite = bunrepo.NewWriteRepository[entities.Suggestion](db.(*bun.DB))
	})

	yolo.MustServe("./app.yml")
}
