// Route tree generated by TanStack Router — regenerated on file changes.
// Manual placeholder until TanStack Start codegen runs.

import { createRootRoute, createRoute } from '@tanstack/react-router'
import { RootLayout } from './routes/__root'
import { IndexPage } from './routes/index'
import { TaskListPage } from './routes/factory/tasks/index'
import { RunListPage } from './routes/factory/runs/index'
import { RepoListPage } from './routes/factory/repos/index'
import { QuestionListPage } from './routes/factory/questions/index'

const rootRoute = createRootRoute({ component: RootLayout })

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: IndexPage,
})

const taskListRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/factory/tasks',
  component: TaskListPage,
})

const runListRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/factory/runs',
  component: RunListPage,
})

const repoListRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/factory/repos',
  component: RepoListPage,
})

const questionListRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/factory/questions',
  component: QuestionListPage,
})

export const routeTree = rootRoute.addChildren([
  indexRoute,
  taskListRoute,
  runListRoute,
  repoListRoute,
  questionListRoute,
])
