// Code generated by yolo gen. DO NOT EDIT.
package insight

import (
	"github.com/yolo-hq/yolo/core/entity"
)

// Insight is a generated entity struct from Blueprint spec.
type Insight struct {
	entity.BaseEntity `bun:",extend"`

	Body           string `bun:"body,notnull" json:"body"`
	Category       string `bun:"category,notnull" json:"category"`
	MetricData     any    `bun:"metric_data,default:'{}'" json:"metric_data"`
	Priority       string `bun:"priority,default:'medium'" json:"priority"`
	ProjectID      string `bun:"project_id,notnull" json:"project_id"`
	Recommendation string `bun:"recommendation,default:''" json:"recommendation"`
	Status         string `bun:"status,default:'pending'" json:"status"`
	Title          string `bun:"title,notnull" json:"title"`
}
