// Code generated by yolo gen. DO NOT EDIT.
package insight

import (
	"context"

	"github.com/yolo-hq/yolo/core/service"
)

// InsightAcknowledgedEvent is the append-only fact emitted for InsightAcknowledged.
type InsightAcknowledgedEvent struct {
	ActorID   string `json:"actor_id"`
	InsightID string `json:"insight_id"`
}

// EmitInsightAcknowledged builds a InsightAcknowledgedEvent and records it on the ctx-scoped
// service event collector.
func EmitInsightAcknowledged(ctx context.Context, actorID string, insightID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "insight_acknowledged",
		Data: InsightAcknowledgedEvent{
			ActorID:   actorID,
			InsightID: insightID,
		},
	})
}

// InsightAppliedEvent is the append-only fact emitted for InsightApplied.
type InsightAppliedEvent struct {
	ActorID   string `json:"actor_id"`
	InsightID string `json:"insight_id"`
}

// EmitInsightApplied builds a InsightAppliedEvent and records it on the ctx-scoped
// service event collector.
func EmitInsightApplied(ctx context.Context, actorID string, insightID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "insight_applied",
		Data: InsightAppliedEvent{
			ActorID:   actorID,
			InsightID: insightID,
		},
	})
}
