// Code generated by yolo gen. DO NOT EDIT.
package insight

import (
	"github.com/yolo-hq/yolo/core/action"

	"github.com/yolo-hq/app-yolo-factory/.yolo/fields"
)

// Insight is the state machine for the Insight entity.
var Insight = action.StateMachine{
	Entity: "Insight",
	Field:  fields.Insight.Status,
	Transitions: action.Transitions{
		"Acknowledge": {From: []string{"pending"}, To: "acknowledged"},
		"Apply":       {From: []string{"acknowledged"}, To: "applied"},
		"Dismiss":     {From: []string{"pending", "acknowledged"}, To: "dismissed"},
	},
}
