// Code generated by yolo gen. DO NOT EDIT.
package review

import (
	"github.com/yolo-hq/yolo/core/entity"
)

// Review is a generated entity struct from Blueprint spec.
type Review struct {
	entity.BaseEntity `bun:",extend"`

	AntiPatterns    any     `bun:"anti_patterns,default:'[]'" json:"anti_patterns"`
	CostUsd         float64 `bun:"cost_usd,default:0" json:"cost_usd"`
	CriteriaResults string  `bun:"criteria_results,notnull" json:"criteria_results"`
	Model           string  `bun:"model,notnull" json:"model"`
	Reasons         any     `bun:"reasons,default:'[]'" json:"reasons"`
	RunID           string  `bun:"run_id,notnull" json:"run_id"`
	SessionID       string  `bun:"session_id" json:"session_id"`
	Suggestions     any     `bun:"suggestions,default:'[]'" json:"suggestions"`
	TaskID          string  `bun:"task_id,notnull" json:"task_id"`
	Verdict         string  `bun:"verdict,notnull" json:"verdict"`
}
