// Code generated by yolo gen. DO NOT EDIT.
package review

import (
	"context"

	"github.com/yolo-hq/yolo/core/service"
)

// ReviewCompletedEvent is the append-only fact emitted for ReviewCompleted.
type ReviewCompletedEvent struct {
	ReviewID string `json:"review_id"`
	Verdict  string `json:"verdict"`
}

// EmitReviewCompleted builds a ReviewCompletedEvent and records it on the ctx-scoped
// service event collector.
func EmitReviewCompleted(ctx context.Context, reviewID string, verdict string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "review_completed",
		Data: ReviewCompletedEvent{
			ReviewID: reviewID,
			Verdict:  verdict,
		},
	})
}
