// Code generated by yolo gen. DO NOT EDIT.
package review

import (
	"github.com/yolo-hq/yolo/core/filter"
)

// ReviewFilter declares the list filters supported for the Review entity.
// Each field is a typed pointer to a core/filter field type; non-nil
// fields are auto-applied to the SQL builder via filter.ApplyStruct.
type ReviewFilter struct {
	filter.Base

	RunID   *filter.IDField     `json:"run_id" filter:"run_id"`
	TaskID  *filter.IDField     `json:"task_id" filter:"task_id"`
	Verdict *filter.StringField `json:"verdict" filter:"verdict"`
}
