// Code generated by yolo. DO NOT EDIT.
package main

import (
	"github.com/yolo-hq/yolo"
	"github.com/yolo-hq/yolo/core/registry"
	bunrepo "github.com/yolo-hq/yolo/core/bun"
	"github.com/uptrace/bun"

	"github.com/yolo-hq/app-yolo-factory/server/factory/entities"
	"github.com/yolo-hq/app-yolo-factory/server/factory/actions"
	"github.com/yolo-hq/app-yolo-factory/server/factory/filters"
)

func main() {
	// Entities
	registry.Register(entities.Question{}, entities.Repo{}, entities.Run{}, entities.Task{})

	// Repositories (typed, created by runtime with db)
	registry.RegisterRepoFactory("Question", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Question](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Question](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Repo", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Repo](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Repo](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Run", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Run](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Run](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Task", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Task](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Task](db.(*bun.DB))
	})

	// Filters
	registry.RegisterFilter("Question", filters.QuestionFilter{})
	registry.RegisterFilter("Run", filters.RunFilter{})
	registry.RegisterFilter("Task", filters.TaskFilter{})

	// Actions
	registry.RegisterActions("Task", &actions.ExecuteTaskAction{}, &actions.CreateTaskAction{}, &actions.UpdateTaskAction{}, &actions.CancelTaskAction{})
	registry.RegisterActions("Question", &actions.CreateQuestionAction{}, &actions.ResolveQuestionAction{})
	registry.RegisterActions("Repo", &actions.CreateRepoAction{}, &actions.UpdateRepoAction{})
	registry.RegisterActions("Run", &actions.CreateRunAction{}, &actions.CompleteRunAction{})

	yolo.MustRunBinary()
}
