// Code generated by yolo. DO NOT EDIT.
package main

import (
	"github.com/yolo-hq/yolo"
	"github.com/yolo-hq/yolo/core/registry"
	bunrepo "github.com/yolo-hq/yolo/core/bun"
	"github.com/uptrace/bun"

	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/entities"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/actions"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/filters"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/commands"
	"github.com/yolo-hq/yolo/core/command"
)

func main() {
	// Entities
	registry.Register(entities.Step{}, entities.Insight{}, entities.LintResult{}, entities.PRD{}, entities.Review{}, entities.Run{}, entities.Suggestion{}, entities.Task{}, entities.Project{}, entities.Question{})

	// Repositories
	registry.RegisterRepoFactory("Step", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Step](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Step](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Insight", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Insight](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Insight](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("LintResult", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.LintResult](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.LintResult](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("PRD", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.PRD](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.PRD](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Review", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Review](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Review](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Run", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Run](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Run](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Suggestion", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Suggestion](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Suggestion](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Task", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Task](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Task](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Project", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Project](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Project](db.(*bun.DB))
	})
	registry.RegisterRepoFactory("Question", func(db any) (any, any) {
		return bunrepo.NewReadRepository[entities.Question](db.(*bun.DB)), bunrepo.NewWriteRepository[entities.Question](db.(*bun.DB))
	})

	// Filters
	registry.RegisterFilter("LintResult", filters.LintResultFilter{})
	registry.RegisterFilter("PRD", filters.PRDFilter{})
	registry.RegisterFilter("Review", filters.ReviewFilter{})
	registry.RegisterFilter("Run", filters.RunFilter{})
	registry.RegisterFilter("Suggestion", filters.SuggestionFilter{})
	registry.RegisterFilter("Task", filters.TaskFilter{})
	registry.RegisterFilter("Insight", filters.InsightFilter{})
	registry.RegisterFilter("Project", filters.ProjectFilter{})
	registry.RegisterFilter("Question", filters.QuestionFilter{})
	registry.RegisterFilter("Step", filters.StepFilter{})

	// Actions
	registry.RegisterActions("Project", &actions.ResumeProjectAction{}, &actions.CreateProjectAction{}, &actions.UpdateProjectAction{}, &actions.PauseProjectAction{})
	registry.RegisterActions("Insight", &actions.ApplyInsightAction{}, &actions.DismissInsightAction{}, &actions.AcknowledgeInsightAction{})
	registry.RegisterActions("PRD", &actions.ExecutePRDAction{}, &actions.ApprovePRDAction{}, &actions.SubmitPRDAction{})
	registry.RegisterActions("Question", &actions.AnswerQuestionAction{})
	registry.RegisterActions("Task", &actions.CancelTaskAction{}, &actions.RetryTaskAction{})
	registry.RegisterActions("Run", &actions.CompleteRunAction{})
	registry.RegisterActions("Suggestion", &actions.RejectSuggestionAction{}, &actions.ApproveSuggestionAction{})

	// Commands
	command.Register(&commands.AdvisorRun{})
	command.Register(&commands.Cost{})
	command.Register(&commands.PRDSubmit{})
	command.Register(&commands.PRDList{})
	command.Register(&commands.PRDGet{})
	command.Register(&commands.PRDApprove{})
	command.Register(&commands.PRDExecute{})
	command.Register(&commands.QuestionList{})
	command.Register(&commands.QuestionAnswer{})
	command.Register(&commands.TaskList{})
	command.Register(&commands.TaskGet{})
	command.Register(&commands.TaskCancel{})
	command.Register(&commands.TaskRetry{})
	command.Register(&commands.Backup{})
	command.Register(&commands.Recover{})
	command.Register(&commands.InsightList{})
	command.Register(&commands.InsightAcknowledge{})
	command.Register(&commands.InsightApply{})
	command.Register(&commands.InsightDismiss{})
	command.Register(&commands.PRDDiff{})
	command.Register(&commands.ProjectAdd{})
	command.Register(&commands.ProjectList{})
	command.Register(&commands.ProjectGet{})
	command.Register(&commands.ProjectUpdate{})
	command.Register(&commands.ProjectPause{})
	command.Register(&commands.ProjectResume{})
	command.Register(&commands.ProjectArchive{})
	command.Register(&commands.ProjectScan{})
	command.Register(&commands.SentinelRun{})
	command.Register(&commands.Status{})
	command.Register(&commands.SuggestionList{})
	command.Register(&commands.SuggestionApprove{})
	command.Register(&commands.SuggestionReject{})

	yolo.MustRunBinary()
}
