// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var PRD = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	ProjectID write.Field[string]
	Title write.Field[string]
	Status write.Field[string]
	Source write.Field[string]
	CreatedBy write.Field[string]
	Body write.Field[string]
	AcceptanceCriteria write.Field[string]
	DesignDecisions write.Field[string]
	TotalTasks write.Field[int]
	CompletedTasks write.Field[int]
	FailedTasks write.Field[int]
	TotalCostUSD write.Field[float64]
	ApprovedAt write.Field[*time.Time]
	CompletedAt write.Field[*time.Time]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	ProjectID: write.NewField[string]("project_id"),
	Title: write.NewField[string]("title"),
	Status: write.NewField[string]("status"),
	Source: write.NewField[string]("source"),
	CreatedBy: write.NewField[string]("created_by"),
	Body: write.NewField[string]("body"),
	AcceptanceCriteria: write.NewField[string]("acceptance_criteria"),
	DesignDecisions: write.NewField[string]("design_decisions"),
	TotalTasks: write.NewField[int]("total_tasks"),
	CompletedTasks: write.NewField[int]("completed_tasks"),
	FailedTasks: write.NewField[int]("failed_tasks"),
	TotalCostUSD: write.NewField[float64]("total_cost_usd"),
	ApprovedAt: write.NewField[*time.Time]("approved_at"),
	CompletedAt: write.NewField[*time.Time]("completed_at"),
}
