// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var Project = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	Name write.Field[string]
	Status write.Field[string]
	RepoURL write.Field[string]
	LocalPath write.Field[string]
	UseWorktrees write.Field[bool]
	DefaultBranch write.Field[string]
	MaintenanceBranches write.Field[string]
	DefaultModel write.Field[string]
	EscalationModel write.Field[string]
	EscalationAfterRetries write.Field[int]
	BudgetPerTaskUSD write.Field[float64]
	BudgetPerPrdUSD write.Field[float64]
	BudgetMonthlyUSD write.Field[float64]
	BudgetWarningAt write.Field[float64]
	SpentThisMonthUSD write.Field[float64]
	MaxRetries write.Field[int]
	TimeoutSecs write.Field[int]
	AutoMerge write.Field[bool]
	AutoStart write.Field[bool]
	PushFailedBranches write.Field[bool]
	SetupCommands write.Field[string]
	TestCommands write.Field[string]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	Name: write.NewField[string]("name"),
	Status: write.NewField[string]("status"),
	RepoURL: write.NewField[string]("repo_url"),
	LocalPath: write.NewField[string]("local_path"),
	UseWorktrees: write.NewField[bool]("use_worktrees"),
	DefaultBranch: write.NewField[string]("default_branch"),
	MaintenanceBranches: write.NewField[string]("maintenance_branches"),
	DefaultModel: write.NewField[string]("default_model"),
	EscalationModel: write.NewField[string]("escalation_model"),
	EscalationAfterRetries: write.NewField[int]("escalation_after_retries"),
	BudgetPerTaskUSD: write.NewField[float64]("budget_per_task_usd"),
	BudgetPerPrdUSD: write.NewField[float64]("budget_per_prd_usd"),
	BudgetMonthlyUSD: write.NewField[float64]("budget_monthly_usd"),
	BudgetWarningAt: write.NewField[float64]("budget_warning_at"),
	SpentThisMonthUSD: write.NewField[float64]("spent_this_month_usd"),
	MaxRetries: write.NewField[int]("max_retries"),
	TimeoutSecs: write.NewField[int]("timeout_secs"),
	AutoMerge: write.NewField[bool]("auto_merge"),
	AutoStart: write.NewField[bool]("auto_start"),
	PushFailedBranches: write.NewField[bool]("push_failed_branches"),
	SetupCommands: write.NewField[string]("setup_commands"),
	TestCommands: write.NewField[string]("test_commands"),
}
