// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var Question = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	TaskID write.Field[string]
	RunID write.Field[string]
	RepoID write.Field[string]
	Status write.Field[string]
	Context write.Field[string]
	Tried write.Field[string]
	Body write.Field[string]
	Resolution write.Field[string]
	Task write.Field[*Task]
	Run write.Field[*Run]
	Repo write.Field[*Repo]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	TaskID: write.NewField[string]("task_id"),
	RunID: write.NewField[string]("run_id"),
	RepoID: write.NewField[string]("repo_id"),
	Status: write.NewField[string]("status"),
	Context: write.NewField[string]("context"),
	Tried: write.NewField[string]("tried"),
	Body: write.NewField[string]("body"),
	Resolution: write.NewField[string]("resolution"),
	Task: write.NewField[*Task]("-"),
	Run: write.NewField[*Run]("-"),
	Repo: write.NewField[*Repo]("-"),
}
