// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var Question = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	TaskID write.Field[string]
	RunID write.Field[string]
	Body write.Field[string]
	Context write.Field[string]
	Confidence write.Field[string]
	Status write.Field[string]
	Answer write.Field[string]
	AnsweredBy write.Field[string]
	AnswerSessionID write.Field[string]
	AnsweredAt write.Field[*time.Time]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	TaskID: write.NewField[string]("task_id"),
	RunID: write.NewField[string]("run_id"),
	Body: write.NewField[string]("body"),
	Context: write.NewField[string]("context"),
	Confidence: write.NewField[string]("confidence"),
	Status: write.NewField[string]("status"),
	Answer: write.NewField[string]("answer"),
	AnsweredBy: write.NewField[string]("answered_by"),
	AnswerSessionID: write.NewField[string]("answer_session_id"),
	AnsweredAt: write.NewField[*time.Time]("answered_at"),
}
