// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var Repo = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	Name write.Field[string]
	URL write.Field[string]
	LocalPath write.Field[string]
	TargetBranch write.Field[string]
	DefaultModel write.Field[string]
	FeedbackLoops write.Field[string]
	Active write.Field[bool]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	Name: write.NewField[string]("name"),
	URL: write.NewField[string]("url"),
	LocalPath: write.NewField[string]("local_path"),
	TargetBranch: write.NewField[string]("target_branch"),
	DefaultModel: write.NewField[string]("default_model"),
	FeedbackLoops: write.NewField[string]("feedback_loops"),
	Active: write.NewField[bool]("active"),
}
