// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var Run = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	TaskID write.Field[string]
	RepoID write.Field[string]
	Agent write.Field[string]
	Model write.Field[string]
	Status write.Field[string]
	Cost write.Field[float64]
	Duration write.Field[int]
	LogURL write.Field[string]
	Error write.Field[string]
	CommitHash write.Field[string]
	StartedAt write.Field[time.Time]
	CompletedAt write.Field[*time.Time]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	TaskID: write.NewField[string]("task_id"),
	RepoID: write.NewField[string]("repo_id"),
	Agent: write.NewField[string]("agent"),
	Model: write.NewField[string]("model"),
	Status: write.NewField[string]("status"),
	Cost: write.NewField[float64]("cost"),
	Duration: write.NewField[int]("duration"),
	LogURL: write.NewField[string]("log_url"),
	Error: write.NewField[string]("error"),
	CommitHash: write.NewField[string]("commit_hash"),
	StartedAt: write.NewField[time.Time]("started_at"),
	CompletedAt: write.NewField[*time.Time]("completed_at"),
}
