// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var Run = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	TaskID write.Field[string]
	AgentType write.Field[string]
	Status write.Field[string]
	Model write.Field[string]
	SessionID write.Field[string]
	SessionName write.Field[string]
	EscalatedModel write.Field[string]
	CostUSD write.Field[float64]
	TokensIn write.Field[int]
	TokensOut write.Field[int]
	DurationMs write.Field[int]
	NumTurns write.Field[int]
	CommitHash write.Field[string]
	BranchName write.Field[string]
	FilesChanged write.Field[string]
	Result write.Field[string]
	Error write.Field[string]
	StartedAt write.Field[time.Time]
	CompletedAt write.Field[*time.Time]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	TaskID: write.NewField[string]("task_id"),
	AgentType: write.NewField[string]("agent_type"),
	Status: write.NewField[string]("status"),
	Model: write.NewField[string]("model"),
	SessionID: write.NewField[string]("session_id"),
	SessionName: write.NewField[string]("session_name"),
	EscalatedModel: write.NewField[string]("escalated_model"),
	CostUSD: write.NewField[float64]("cost_usd"),
	TokensIn: write.NewField[int]("tokens_in"),
	TokensOut: write.NewField[int]("tokens_out"),
	DurationMs: write.NewField[int]("duration_ms"),
	NumTurns: write.NewField[int]("num_turns"),
	CommitHash: write.NewField[string]("commit_hash"),
	BranchName: write.NewField[string]("branch_name"),
	FilesChanged: write.NewField[string]("files_changed"),
	Result: write.NewField[string]("result"),
	Error: write.NewField[string]("error"),
	StartedAt: write.NewField[time.Time]("started_at"),
	CompletedAt: write.NewField[*time.Time]("completed_at"),
}
