// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var Step = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	RunID write.Field[string]
	Phase write.Field[string]
	Skill write.Field[string]
	Status write.Field[string]
	Model write.Field[string]
	SessionID write.Field[string]
	CostUSD write.Field[float64]
	TokensIn write.Field[int]
	TokensOut write.Field[int]
	DurationMs write.Field[int]
	InputSummary write.Field[string]
	OutputSummary write.Field[string]
	StartedAt write.Field[time.Time]
	CompletedAt write.Field[*time.Time]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	RunID: write.NewField[string]("run_id"),
	Phase: write.NewField[string]("phase"),
	Skill: write.NewField[string]("skill"),
	Status: write.NewField[string]("status"),
	Model: write.NewField[string]("model"),
	SessionID: write.NewField[string]("session_id"),
	CostUSD: write.NewField[float64]("cost_usd"),
	TokensIn: write.NewField[int]("tokens_in"),
	TokensOut: write.NewField[int]("tokens_out"),
	DurationMs: write.NewField[int]("duration_ms"),
	InputSummary: write.NewField[string]("input_summary"),
	OutputSummary: write.NewField[string]("output_summary"),
	StartedAt: write.NewField[time.Time]("started_at"),
	CompletedAt: write.NewField[*time.Time]("completed_at"),
}
