// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var Suggestion = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	ProjectID write.Field[string]
	Source write.Field[string]
	Category write.Field[string]
	Title write.Field[string]
	Body write.Field[string]
	Priority write.Field[string]
	Status write.Field[string]
	ConvertedTaskID write.Field[string]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	ProjectID: write.NewField[string]("project_id"),
	Source: write.NewField[string]("source"),
	Category: write.NewField[string]("category"),
	Title: write.NewField[string]("title"),
	Body: write.NewField[string]("body"),
	Priority: write.NewField[string]("priority"),
	Status: write.NewField[string]("status"),
	ConvertedTaskID: write.NewField[string]("converted_task_id"),
}
