// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var Task = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	RepoID write.Field[string]
	Title write.Field[string]
	Body write.Field[string]
	Type write.Field[string]
	Status write.Field[string]
	Priority write.Field[int]
	Model write.Field[string]
	Labels write.Field[string]
	ParentID write.Field[string]
	DependsOn write.Field[string]
	Cost write.Field[float64]
	RunCount write.Field[int]
	MaxRetries write.Field[int]
	TimeoutSecs write.Field[int]
	Repo write.Field[*Repo]
	Parent write.Field[*Task]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	RepoID: write.NewField[string]("repo_id"),
	Title: write.NewField[string]("title"),
	Body: write.NewField[string]("body"),
	Type: write.NewField[string]("type"),
	Status: write.NewField[string]("status"),
	Priority: write.NewField[int]("priority"),
	Model: write.NewField[string]("model"),
	Labels: write.NewField[string]("labels"),
	ParentID: write.NewField[string]("parent_id"),
	DependsOn: write.NewField[string]("depends_on"),
	Cost: write.NewField[float64]("cost"),
	RunCount: write.NewField[int]("run_count"),
	MaxRetries: write.NewField[int]("max_retries"),
	TimeoutSecs: write.NewField[int]("timeout_secs"),
	Repo: write.NewField[*Repo]("-"),
	Parent: write.NewField[*Task]("-"),
}
