// Code generated by yolo generate fields. DO NOT EDIT.
package fields

import (
	"time"
	"github.com/yolo-hq/yolo/core/write"
)

var Task = struct {
	ID write.Field[string]
	CreatedAt write.Field[time.Time]
	UpdatedAt write.Field[time.Time]
	DeletedAt write.Field[*time.Time]
	PrdID write.Field[string]
	ProjectID write.Field[string]
	Title write.Field[string]
	Status write.Field[string]
	Spec write.Field[string]
	AcceptanceCriteria write.Field[string]
	Branch write.Field[string]
	Model write.Field[string]
	Sequence write.Field[int]
	DependsOn write.Field[string]
	RunCount write.Field[int]
	MaxRetries write.Field[int]
	CostUSD write.Field[float64]
	Summary write.Field[string]
	CommitHash write.Field[string]
	StartedAt write.Field[*time.Time]
	CompletedAt write.Field[*time.Time]
}{
	ID: write.NewField[string]("id"),
	CreatedAt: write.NewField[time.Time]("created_at"),
	UpdatedAt: write.NewField[time.Time]("updated_at"),
	DeletedAt: write.NewField[*time.Time]("deleted_at"),
	PrdID: write.NewField[string]("prd_id"),
	ProjectID: write.NewField[string]("project_id"),
	Title: write.NewField[string]("title"),
	Status: write.NewField[string]("status"),
	Spec: write.NewField[string]("spec"),
	AcceptanceCriteria: write.NewField[string]("acceptance_criteria"),
	Branch: write.NewField[string]("branch"),
	Model: write.NewField[string]("model"),
	Sequence: write.NewField[int]("sequence"),
	DependsOn: write.NewField[string]("depends_on"),
	RunCount: write.NewField[int]("run_count"),
	MaxRetries: write.NewField[int]("max_retries"),
	CostUSD: write.NewField[float64]("cost_usd"),
	Summary: write.NewField[string]("summary"),
	CommitHash: write.NewField[string]("commit_hash"),
	StartedAt: write.NewField[*time.Time]("started_at"),
	CompletedAt: write.NewField[*time.Time]("completed_at"),
}
