// Code generated by yolo gen. DO NOT EDIT.

package actions

import (
	"context"
	"github.com/yolo-hq/yolo/core/action"
	"github.com/yolo-hq/yolo/core/policy"
	"github.com/yolo-hq/yolo/core/registry"
)

type InsightAcknowledgeAction struct{}

func (InsightAcknowledgeAction) Name() string        { return "insight:acknowledge" }
func (InsightAcknowledgeAction) Description() string { return "Acknowledges a pending insight." }
func (InsightAcknowledgeAction) Kind() string        { return "action" }
func (InsightAcknowledgeAction) Policies() []action.AnyPolicy {
	var out []action.AnyPolicy
	if p, ok := policy.Get("policies.CanAcknowledgeInsightPolicy"); ok {
		out = append(out, p)
	}
	return out
}

func (InsightAcknowledgeAction) Execute(ctx context.Context, actx *action.Context) error {
	return InsightAcknowledge(ctx, actx)
}

func init() {
	registry.RegisterActions("Insight", InsightAcknowledgeAction{})
}

type InsightApplyAction struct{}

func (InsightApplyAction) Name() string        { return "insight:apply" }
func (InsightApplyAction) Description() string { return "Applies an acknowledged insight." }
func (InsightApplyAction) Kind() string        { return "action" }
func (InsightApplyAction) Policies() []action.AnyPolicy {
	var out []action.AnyPolicy
	if p, ok := policy.Get("policies.CanApplyInsightPolicy"); ok {
		out = append(out, p)
	}
	return out
}

func (InsightApplyAction) Execute(ctx context.Context, actx *action.Context) error {
	return InsightApply(ctx, actx)
}

func init() {
	registry.RegisterActions("Insight", InsightApplyAction{})
}

type InsightDismissAction struct{}

func (InsightDismissAction) Name() string        { return "insight:dismiss" }
func (InsightDismissAction) Description() string { return "Dismisses an insight." }
func (InsightDismissAction) Kind() string        { return "action" }
func (InsightDismissAction) Policies() []action.AnyPolicy {
	var out []action.AnyPolicy
	if p, ok := policy.Get("policies.CanDismissInsightPolicy"); ok {
		out = append(out, p)
	}
	return out
}

func (InsightDismissAction) Execute(ctx context.Context, actx *action.Context) error {
	return InsightDismiss(ctx, actx)
}

func init() {
	registry.RegisterActions("Insight", InsightDismissAction{})
}

type PRDApproveAction struct{}

func (PRDApproveAction) Name() string { return "prd:approve" }
func (PRDApproveAction) Description() string {
	return "Approves a draft PRD and optionally triggers planning."
}
func (PRDApproveAction) Kind() string { return "action" }
func (PRDApproveAction) Policies() []action.AnyPolicy {
	var out []action.AnyPolicy
	if p, ok := policy.Get("policies.CanApprovePRDPolicy"); ok {
		out = append(out, p)
	}
	return out
}

func (PRDApproveAction) Execute(ctx context.Context, actx *action.Context) error {
	return PRDApprove(ctx, actx)
}

func init() {
	registry.RegisterActions("PRD", PRDApproveAction{})
}

type ProjectArchiveAction struct{}

func (ProjectArchiveAction) Name() string        { return "project:archive" }
func (ProjectArchiveAction) Description() string { return "Archives an active project." }
func (ProjectArchiveAction) Kind() string        { return "action" }
func (ProjectArchiveAction) Policies() []action.AnyPolicy {
	var out []action.AnyPolicy
	if p, ok := policy.Get("policies.CanArchiveProjectPolicy"); ok {
		out = append(out, p)
	}
	return out
}

func (ProjectArchiveAction) Execute(ctx context.Context, actx *action.Context) error {
	return ProjectArchive(ctx, actx)
}

func init() {
	registry.RegisterActions("Project", ProjectArchiveAction{})
}

type ProjectPauseAction struct{}

func (ProjectPauseAction) Name() string        { return "project:pause" }
func (ProjectPauseAction) Description() string { return "Pauses an active project." }
func (ProjectPauseAction) Kind() string        { return "action" }
func (ProjectPauseAction) Policies() []action.AnyPolicy {
	var out []action.AnyPolicy
	if p, ok := policy.Get("policies.CanPauseProjectPolicy"); ok {
		out = append(out, p)
	}
	return out
}

func (ProjectPauseAction) Execute(ctx context.Context, actx *action.Context) error {
	return ProjectPause(ctx, actx)
}

func init() {
	registry.RegisterActions("Project", ProjectPauseAction{})
}

type ProjectResumeAction struct{}

func (ProjectResumeAction) Name() string        { return "project:resume" }
func (ProjectResumeAction) Description() string { return "Resumes a paused project." }
func (ProjectResumeAction) Kind() string        { return "action" }
func (ProjectResumeAction) Policies() []action.AnyPolicy {
	var out []action.AnyPolicy
	if p, ok := policy.Get("policies.CanResumeProjectPolicy"); ok {
		out = append(out, p)
	}
	return out
}

func (ProjectResumeAction) Execute(ctx context.Context, actx *action.Context) error {
	return ProjectResume(ctx, actx)
}

func init() {
	registry.RegisterActions("Project", ProjectResumeAction{})
}

type TaskCancelAction struct{}

func (TaskCancelAction) Name() string        { return "task:cancel" }
func (TaskCancelAction) Description() string { return "Cancels a non-terminal task." }
func (TaskCancelAction) Kind() string        { return "action" }
func (TaskCancelAction) Policies() []action.AnyPolicy {
	var out []action.AnyPolicy
	if p, ok := policy.Get("policies.CanCancelTaskPolicy"); ok {
		out = append(out, p)
	}
	return out
}

func (TaskCancelAction) Execute(ctx context.Context, actx *action.Context) error {
	return TaskCancel(ctx, actx)
}

func init() {
	registry.RegisterActions("Task", TaskCancelAction{})
}
