CREATE TABLE factory_projects (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'active',
    repo_url TEXT NOT NULL,
    local_path TEXT NOT NULL DEFAULT '',
    use_worktrees BOOLEAN DEFAULT FALSE,
    default_branch TEXT NOT NULL DEFAULT 'main',
    maintenance_branches TEXT DEFAULT '[]',
    default_model TEXT NOT NULL DEFAULT 'sonnet',
    escalation_model TEXT NOT NULL DEFAULT 'opus',
    escalation_after_retries INTEGER NOT NULL DEFAULT 2,
    budget_per_task_usd REAL NOT NULL DEFAULT 2.0,
    budget_per_prd_usd REAL NOT NULL DEFAULT 20.0,
    budget_monthly_usd REAL NOT NULL DEFAULT 200.0,
    budget_warning_at REAL NOT NULL DEFAULT 0.8,
    spent_this_month_usd REAL NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 3,
    timeout_secs INTEGER NOT NULL DEFAULT 600,
    auto_merge BOOLEAN NOT NULL DEFAULT TRUE,
    auto_start BOOLEAN NOT NULL DEFAULT FALSE,
    push_failed_branches BOOLEAN NOT NULL DEFAULT FALSE,
    setup_commands TEXT DEFAULT '[]',
    test_commands TEXT DEFAULT '["go build ./...","go test ./..."]',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);
