CREATE TABLE factory_runs (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL REFERENCES factory_tasks(id),
    agent_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'running',
    model TEXT NOT NULL,
    session_id TEXT,
    session_name TEXT,
    escalated_model TEXT,
    cost_usd REAL DEFAULT 0,
    tokens_in INTEGER DEFAULT 0,
    tokens_out INTEGER DEFAULT 0,
    duration_ms INTEGER DEFAULT 0,
    num_turns INTEGER DEFAULT 0,
    commit_hash TEXT,
    branch_name TEXT,
    files_changed TEXT DEFAULT '[]',
    result TEXT,
    error TEXT,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);
