// Code generated by yolo gen. DO NOT EDIT.
package prd

import (
	"time"

	"github.com/yolo-hq/yolo/core/entity"
)

// PRD is a generated entity struct from Blueprint spec.
type PRD struct {
	entity.BaseEntity `bun:",extend"`

	AcceptanceCriteria string     `bun:"acceptance_criteria,notnull" json:"acceptance_criteria"`
	ApprovedAt         *time.Time `bun:"approved_at" json:"approved_at"`
	Body               string     `bun:"body,notnull" json:"body"`
	CompletedAt        *time.Time `bun:"completed_at" json:"completed_at"`
	CreatedBy          string     `bun:"created_by,default:'human'" json:"created_by"`
	DesignDecisions    any        `bun:"design_decisions,default:'[]'" json:"design_decisions"`
	FailedTasks        int        `bun:"failed_tasks,default:0" json:"failed_tasks"`
	ProjectID          string     `bun:"project_id,notnull" json:"project_id"`
	Source             string     `bun:"source,default:'manual'" json:"source"`
	Status             string     `bun:"status,default:'draft'" json:"status"`
	Title              string     `bun:"title,notnull" json:"title"`
}
