// Code generated by yolo gen. DO NOT EDIT.
package prd

import (
	"context"

	"github.com/yolo-hq/yolo/core/service"
)

// PrdapprovedEvent is the append-only fact emitted for PRDApproved.
type PrdapprovedEvent struct {
	ActorID string `json:"actor_id"`
	PrdID   string `json:"prd_id"`
}

// EmitPrdapproved builds a PrdapprovedEvent and records it on the ctx-scoped
// service event collector.
func EmitPrdapproved(ctx context.Context, actorID string, prdID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "prd_approved",
		Data: PrdapprovedEvent{
			ActorID: actorID,
			PrdID:   prdID,
		},
	})
}

// PrdcompletedEvent is the append-only fact emitted for PRDCompleted.
type PrdcompletedEvent struct {
	ActorID string `json:"actor_id"`
	PrdID   string `json:"prd_id"`
}

// EmitPrdcompleted builds a PrdcompletedEvent and records it on the ctx-scoped
// service event collector.
func EmitPrdcompleted(ctx context.Context, actorID string, prdID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "prd_completed",
		Data: PrdcompletedEvent{
			ActorID: actorID,
			PrdID:   prdID,
		},
	})
}

// PrdfailedEvent is the append-only fact emitted for PRDFailed.
type PrdfailedEvent struct {
	ActorID string `json:"actor_id"`
	PrdID   string `json:"prd_id"`
}

// EmitPrdfailed builds a PrdfailedEvent and records it on the ctx-scoped
// service event collector.
func EmitPrdfailed(ctx context.Context, actorID string, prdID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "prd_failed",
		Data: PrdfailedEvent{
			ActorID: actorID,
			PrdID:   prdID,
		},
	})
}
