// Code generated by yolo gen. DO NOT EDIT.
package prd

import (
	"github.com/yolo-hq/yolo/core/filter"
)

// PrdFilter declares the list filters supported for the Prd entity.
// Each field is a typed pointer to a core/filter field type; non-nil
// fields are auto-applied to the SQL builder via filter.ApplyStruct.
type PrdFilter struct {
	filter.Base

	ProjectID *filter.IDField     `json:"project_id" filter:"project_id"`
	Source    *filter.StringField `json:"source" filter:"source"`
	Status    *filter.StringField `json:"status" filter:"status"`
}
