// Code generated by yolo gen. DO NOT EDIT.
package prd

import (
	"github.com/yolo-hq/yolo/core/action"

	"github.com/yolo-hq/app-yolo-factory/.yolo/fields"
)

// Prd is the state machine for the Prd entity.
var Prd = action.StateMachine{
	Entity: "Prd",
	Field:  fields.Prd.Status,
	Transitions: action.Transitions{
		"Approve":  {From: []string{"draft"}, To: "approved"},
		"Complete": {From: []string{"in_progress"}, To: "completed"},
		"Fail":     {From: []string{"in_progress"}, To: "failed"},
		"Plan":     {From: []string{"approved"}, To: "planning"},
		"Start":    {From: []string{"planning"}, To: "in_progress"},
	},
}
