// Code generated by yolo gen. DO NOT EDIT.
package step

import (
	"time"

	"github.com/yolo-hq/yolo/core/entity"
)

// Step is a generated entity struct from Blueprint spec.
type Step struct {
	entity.BaseEntity `bun:",extend"`

	CompletedAt   *time.Time `bun:"completed_at" json:"completed_at"`
	CostUsd       float64    `bun:"cost_usd,default:0" json:"cost_usd"`
	DurationMs    int        `bun:"duration_ms,default:0" json:"duration_ms"`
	InputSummary  string     `bun:"input_summary" json:"input_summary"`
	Model         string     `bun:"model,notnull" json:"model"`
	OutputSummary string     `bun:"output_summary" json:"output_summary"`
	Phase         string     `bun:"phase,notnull" json:"phase"`
	ResultStatus  *string    `bun:"result_status" json:"result_status"`
	RunID         string     `bun:"run_id,notnull" json:"run_id"`
	SessionID     string     `bun:"session_id" json:"session_id"`
	Skill         string     `bun:"skill,notnull" json:"skill"`
	StartedAt     time.Time  `bun:"started_at,default:current_timestamp" json:"started_at"`
	Status        string     `bun:"status,default:'running'" json:"status"`
	TokensIn      int        `bun:"tokens_in,default:0" json:"tokens_in"`
	TokensOut     int        `bun:"tokens_out,default:0" json:"tokens_out"`
	Turns         int        `bun:"turns,default:0" json:"turns"`
}
