// Code generated by yolo gen. DO NOT EDIT.
package step

import (
	"github.com/yolo-hq/yolo/core/filter"
)

// StepFilter declares the list filters supported for the Step entity.
// Each field is a typed pointer to a core/filter field type; non-nil
// fields are auto-applied to the SQL builder via filter.ApplyStruct.
type StepFilter struct {
	filter.Base

	Phase  *filter.StringField `json:"phase" filter:"phase"`
	RunID  *filter.IDField     `json:"run_id" filter:"run_id"`
	Status *filter.StringField `json:"status" filter:"status"`
}
