// Code generated by yolo gen. DO NOT EDIT.
package suggestion

import (
	"github.com/yolo-hq/yolo/core/entity"
)

// Suggestion is a generated entity struct from Blueprint spec.
type Suggestion struct {
	entity.BaseEntity `bun:",extend"`

	Body            string  `bun:"body,notnull" json:"body"`
	Category        string  `bun:"category,notnull" json:"category"`
	ConvertedTaskID *string `bun:"converted_task_id" json:"converted_task_id"`
	Priority        string  `bun:"priority,default:'medium'" json:"priority"`
	ProjectID       string  `bun:"project_id,notnull" json:"project_id"`
	Source          string  `bun:"source,notnull" json:"source"`
	Status          string  `bun:"status,default:'pending'" json:"status"`
	Title           string  `bun:"title,notnull" json:"title"`
}
