// Code generated by yolo gen. DO NOT EDIT.
package suggestion

import (
	"github.com/yolo-hq/yolo/core/filter"
)

// SuggestionFilter declares the list filters supported for the Suggestion entity.
// Each field is a typed pointer to a core/filter field type; non-nil
// fields are auto-applied to the SQL builder via filter.ApplyStruct.
type SuggestionFilter struct {
	filter.Base

	Category  *filter.StringField `json:"category" filter:"category"`
	Priority  *filter.StringField `json:"priority" filter:"priority,in"`
	ProjectID *filter.IDField     `json:"project_id" filter:"project_id"`
	Source    *filter.StringField `json:"source" filter:"source"`
	Status    *filter.StringField `json:"status" filter:"status"`
}
