// Code generated by yolo gen. DO NOT EDIT.
package suggestion

import (
	"github.com/yolo-hq/yolo/core/action"

	"github.com/yolo-hq/app-yolo-factory/.yolo/fields"
)

// Suggestion is the state machine for the Suggestion entity.
var Suggestion = action.StateMachine{
	Entity: "Suggestion",
	Field:  fields.Suggestion.Status,
	Transitions: action.Transitions{
		"Approve": {From: []string{"pending"}, To: "approved"},
		"Convert": {From: []string{"approved"}, To: "converted"},
		"Reject":  {From: []string{"pending"}, To: "rejected"},
	},
}
