// Code generated by yolo gen. DO NOT EDIT.
package project

import (
	"github.com/yolo-hq/yolo/core/entity"
)

// Project is a generated entity struct from Blueprint spec.
type Project struct {
	entity.BaseEntity `bun:",extend"`

	AutoMerge              bool    `bun:"auto_merge,default:true" json:"auto_merge"`
	AutoStart              bool    `bun:"auto_start,default:false" json:"auto_start"`
	BudgetMonthlyUsd       float64 `bun:"budget_monthly_usd,default:200" json:"budget_monthly_usd"`
	BudgetPerPRDUsd        float64 `bun:"budget_per_prd_usd,default:20" json:"budget_per_prd_usd"`
	BudgetPerTaskUsd       float64 `bun:"budget_per_task_usd,default:2" json:"budget_per_task_usd"`
	BudgetWarningAt        float64 `bun:"budget_warning_at,default:0.8" json:"budget_warning_at"`
	DefaultBranch          string  `bun:"default_branch,default:'main'" json:"default_branch"`
	DefaultModel           string  `bun:"default_model,default:'sonnet'" json:"default_model"`
	EscalationAfterRetries int     `bun:"escalation_after_retries,default:2" json:"escalation_after_retries"`
	EscalationModel        string  `bun:"escalation_model,default:'opus'" json:"escalation_model"`
	LocalPath              string  `bun:"local_path,default:''" json:"local_path"`
	MaintenanceBranches    any     `bun:"maintenance_branches,default:'[]'" json:"maintenance_branches"`
	MaxRetries             int     `bun:"max_retries,default:3" json:"max_retries"`
	Name                   string  `bun:"name,notnull" json:"name"`
	PushFailedBranches     bool    `bun:"push_failed_branches,default:false" json:"push_failed_branches"`
	RepoURL                string  `bun:"repo_url,notnull" json:"repo_url"`
	SetupCommands          any     `bun:"setup_commands,default:'[]'" json:"setup_commands"`
	SpentThisMonthUsd      float64 `bun:"spent_this_month_usd,default:0" json:"spent_this_month_usd"`
	Status                 string  `bun:"status,default:'active'" json:"status"`
	TestCommands           any     `bun:"test_commands,default:'[]'" json:"test_commands"`
	TimeoutSecs            int     `bun:"timeout_secs,default:600" json:"timeout_secs"`
	UseWorktrees           bool    `bun:"use_worktrees,default:false" json:"use_worktrees"`
}
