// Code generated by yolo gen. DO NOT EDIT.
package project

import (
	"context"

	"github.com/yolo-hq/yolo/core/service"
)

// ProjectArchivedEvent is the append-only fact emitted for ProjectArchived.
type ProjectArchivedEvent struct {
	ActorID   string `json:"actor_id"`
	ProjectID string `json:"project_id"`
}

// EmitProjectArchived builds a ProjectArchivedEvent and records it on the ctx-scoped
// service event collector.
func EmitProjectArchived(ctx context.Context, actorID string, projectID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "project_archived",
		Data: ProjectArchivedEvent{
			ActorID:   actorID,
			ProjectID: projectID,
		},
	})
}

// ProjectCreatedEvent is the append-only fact emitted for ProjectCreated.
type ProjectCreatedEvent struct {
	ActorID   string `json:"actor_id"`
	ProjectID string `json:"project_id"`
}

// EmitProjectCreated builds a ProjectCreatedEvent and records it on the ctx-scoped
// service event collector.
func EmitProjectCreated(ctx context.Context, actorID string, projectID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "project_created",
		Data: ProjectCreatedEvent{
			ActorID:   actorID,
			ProjectID: projectID,
		},
	})
}
