// Code generated by yolo gen. DO NOT EDIT.
package project

import (
	"github.com/yolo-hq/yolo/core/filter"
)

// ProjectFilter declares the list filters supported for the Project entity.
// Each field is a typed pointer to a core/filter field type; non-nil
// fields are auto-applied to the SQL builder via filter.ApplyStruct.
type ProjectFilter struct {
	filter.Base

	Name   *filter.StringField `json:"name" filter:"name"`
	Status *filter.StringField `json:"status" filter:"status"`
}
