// Code generated by yolo gen. DO NOT EDIT.
package question

import (
	"time"

	"github.com/yolo-hq/yolo/core/entity"
)

// Question is a generated entity struct from Blueprint spec.
type Question struct {
	entity.BaseEntity `bun:",extend"`

	Answer          string     `bun:"answer" json:"answer"`
	AnswerSessionID string     `bun:"answer_session_id" json:"answer_session_id"`
	AnsweredAt      *time.Time `bun:"answered_at" json:"answered_at"`
	AnsweredBy      string     `bun:"answered_by" json:"answered_by"`
	Body            string     `bun:"body,notnull" json:"body"`
	Confidence      string     `bun:"confidence,notnull" json:"confidence"`
	Context         string     `bun:"context" json:"context"`
	RunID           string     `bun:"run_id,notnull" json:"run_id"`
	Status          string     `bun:"status,default:'open'" json:"status"`
	TaskID          string     `bun:"task_id,notnull" json:"task_id"`
}
