// Code generated by yolo gen. DO NOT EDIT.
package question

import (
	"context"

	"github.com/yolo-hq/yolo/core/service"
)

// QuestionAnsweredEvent is the append-only fact emitted for QuestionAnswered.
type QuestionAnsweredEvent struct {
	AnsweredBy string `json:"answered_by"`
	QuestionID string `json:"question_id"`
}

// EmitQuestionAnswered builds a QuestionAnsweredEvent and records it on the ctx-scoped
// service event collector.
func EmitQuestionAnswered(ctx context.Context, answeredBy string, questionID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "question_answered",
		Data: QuestionAnsweredEvent{
			AnsweredBy: answeredBy,
			QuestionID: questionID,
		},
	})
}

// QuestionAskedEvent is the append-only fact emitted for QuestionAsked.
type QuestionAskedEvent struct {
	QuestionID string `json:"question_id"`
	TaskID     string `json:"task_id"`
}

// EmitQuestionAsked builds a QuestionAskedEvent and records it on the ctx-scoped
// service event collector.
func EmitQuestionAsked(ctx context.Context, questionID string, taskID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "question_asked",
		Data: QuestionAskedEvent{
			QuestionID: questionID,
			TaskID:     taskID,
		},
	})
}
