// Code generated by yolo gen. DO NOT EDIT.
package question

import (
	"github.com/yolo-hq/yolo/core/filter"
)

// QuestionFilter declares the list filters supported for the Question entity.
// Each field is a typed pointer to a core/filter field type; non-nil
// fields are auto-applied to the SQL builder via filter.ApplyStruct.
type QuestionFilter struct {
	filter.Base

	RunID  *filter.IDField     `json:"run_id" filter:"run_id"`
	Status *filter.StringField `json:"status" filter:"status"`
	TaskID *filter.IDField     `json:"task_id" filter:"task_id"`
}
