// Code generated by yolo gen. DO NOT EDIT.
package question

import (
	"github.com/yolo-hq/yolo/core/action"

	"github.com/yolo-hq/app-yolo-factory/.yolo/fields"
)

// Question is the state machine for the Question entity.
var Question = action.StateMachine{
	Entity: "Question",
	Field:  fields.Question.Status,
	Transitions: action.Transitions{
		"Answer":      {From: []string{"open"}, To: "answered"},
		"AutoResolve": {From: []string{"open"}, To: "auto_resolved"},
	},
}
