// Code generated by yolo gen. DO NOT EDIT.

package queries

import (
	"context"
	"github.com/yolo-hq/app-yolo-factory/apps/common/factory/inputs"
	"github.com/yolo-hq/yolo/core/query"
	"github.com/yolo-hq/yolo/core/registry"
)

type CostQuery struct{}

func (CostQuery) Name() string        { return "cost" }
func (CostQuery) Description() string { return "Cost shows a cost breakdown grouped by model." }
func (CostQuery) Kind() string        { return "query" }
func (CostQuery) InputType() any      { return *new(inputs.CostInput) }

func (CostQuery) Execute(ctx context.Context, qctx *query.Context) error {
	var in inputs.CostInput
	if raw := qctx.Input(); raw != nil {
		if typed, ok := raw.(*inputs.CostInput); ok && typed != nil {
			in = *typed
		} else if typed, ok := raw.(inputs.CostInput); ok {
			in = typed
		}
	}
	out, err := Cost(ctx, qctx, in)
	if err != nil {
		return err
	}
	qctx.Respond(out)
	return nil
}

func init() {
	registry.RegisterQueries("Cost", CostQuery{})
}

type PRDDiffQuery struct{}

func (PRDDiffQuery) Name() string { return "prd:diff" }
func (PRDDiffQuery) Description() string {
	return "Computes the combined git diff for a completed PRD."
}
func (PRDDiffQuery) Kind() string   { return "query" }
func (PRDDiffQuery) InputType() any { return *new(inputs.DiffPRDInput) }

func (PRDDiffQuery) Execute(ctx context.Context, qctx *query.Context) error {
	var in inputs.DiffPRDInput
	if raw := qctx.Input(); raw != nil {
		if typed, ok := raw.(*inputs.DiffPRDInput); ok && typed != nil {
			in = *typed
		} else if typed, ok := raw.(inputs.DiffPRDInput); ok {
			in = typed
		}
	}
	out, err := PRDDiff(ctx, qctx, in)
	if err != nil {
		return err
	}
	qctx.Respond(out)
	return nil
}

func init() {
	registry.RegisterQueries("PRD", PRDDiffQuery{})
}

type StatusQuery struct{}

func (StatusQuery) Name() string        { return "status" }
func (StatusQuery) Description() string { return "Status shows a factory dashboard summary." }
func (StatusQuery) Kind() string        { return "query" }
func (StatusQuery) InputType() any      { return *new(StatusInput) }

func (StatusQuery) Execute(ctx context.Context, qctx *query.Context) error {
	var in StatusInput
	if raw := qctx.Input(); raw != nil {
		if typed, ok := raw.(*StatusInput); ok && typed != nil {
			in = *typed
		} else if typed, ok := raw.(StatusInput); ok {
			in = typed
		}
	}
	out, err := Status(ctx, qctx, in)
	if err != nil {
		return err
	}
	qctx.Respond(out)
	return nil
}

func init() {
	registry.RegisterQueries("Status", StatusQuery{})
}
