// Code generated by yolo gen. DO NOT EDIT.
package run

import (
	"time"

	"github.com/yolo-hq/yolo/core/entity"
)

// Run is a generated entity struct from Blueprint spec.
type Run struct {
	entity.BaseEntity `bun:",extend"`

	AgentType      string     `bun:"agent_type,notnull" json:"agent_type"`
	BranchName     string     `bun:"branch_name" json:"branch_name"`
	CommitHash     string     `bun:"commit_hash" json:"commit_hash"`
	CompletedAt    *time.Time `bun:"completed_at" json:"completed_at"`
	CostUsd        float64    `bun:"cost_usd,default:0" json:"cost_usd"`
	DurationMs     int        `bun:"duration_ms,default:0" json:"duration_ms"`
	Error          string     `bun:"error" json:"error"`
	EscalatedModel string     `bun:"escalated_model" json:"escalated_model"`
	FilesChanged   any        `bun:"files_changed,default:'[]'" json:"files_changed"`
	Model          string     `bun:"model,notnull" json:"model"`
	NumTurns       int        `bun:"num_turns,default:0" json:"num_turns"`
	Result         string     `bun:"result" json:"result"`
	SessionID      string     `bun:"session_id" json:"session_id"`
	SessionName    string     `bun:"session_name" json:"session_name"`
	StartedAt      time.Time  `bun:"started_at,default:current_timestamp" json:"started_at"`
	Status         string     `bun:"status,default:'running'" json:"status"`
	TaskID         string     `bun:"task_id,notnull" json:"task_id"`
	TokensIn       int        `bun:"tokens_in,default:0" json:"tokens_in"`
	TokensOut      int        `bun:"tokens_out,default:0" json:"tokens_out"`
}
