// Code generated by yolo gen. DO NOT EDIT.
package run

import (
	"context"

	"github.com/yolo-hq/yolo/core/service"
)

// RunCompletedEvent is the append-only fact emitted for RunCompleted.
type RunCompletedEvent struct {
	CostUsd float64 `json:"cost_usd"`
	RunID   string  `json:"run_id"`
}

// EmitRunCompleted builds a RunCompletedEvent and records it on the ctx-scoped
// service event collector.
func EmitRunCompleted(ctx context.Context, costUsd float64, runID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "run_completed",
		Data: RunCompletedEvent{
			CostUsd: costUsd,
			RunID:   runID,
		},
	})
}

// RunFailedEvent is the append-only fact emitted for RunFailed.
type RunFailedEvent struct {
	Error string `json:"error"`
	RunID string `json:"run_id"`
}

// EmitRunFailed builds a RunFailedEvent and records it on the ctx-scoped
// service event collector.
func EmitRunFailed(ctx context.Context, error string, runID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "run_failed",
		Data: RunFailedEvent{
			Error: error,
			RunID: runID,
		},
	})
}

// RunStartedEvent is the append-only fact emitted for RunStarted.
type RunStartedEvent struct {
	RunID  string `json:"run_id"`
	TaskID string `json:"task_id"`
}

// EmitRunStarted builds a RunStartedEvent and records it on the ctx-scoped
// service event collector.
func EmitRunStarted(ctx context.Context, runID string, taskID string) {
	service.EmitEvent(ctx, service.PendingEvent{
		Name: "run_started",
		Data: RunStartedEvent{
			RunID:  runID,
			TaskID: taskID,
		},
	})
}
