// Code generated by yolo gen. DO NOT EDIT.
package run

import (
	"github.com/yolo-hq/yolo/core/filter"
)

// RunFilter declares the list filters supported for the Run entity.
// Each field is a typed pointer to a core/filter field type; non-nil
// fields are auto-applied to the SQL builder via filter.ApplyStruct.
type RunFilter struct {
	filter.Base

	Model  *filter.StringField `json:"model" filter:"model"`
	Status *filter.StringField `json:"status" filter:"status"`
	TaskID *filter.IDField     `json:"task_id" filter:"task_id"`
}
