// Code generated by yolo gen. DO NOT EDIT.
package run

import (
	"github.com/yolo-hq/yolo/core/action"

	"github.com/yolo-hq/app-yolo-factory/.yolo/fields"
)

// Run is the state machine for the Run entity.
var Run = action.StateMachine{
	Entity: "Run",
	Field:  fields.Run.Status,
	Transitions: action.Transitions{
		"Block":    {From: []string{"running"}, To: "blocked"},
		"Cancel":   {From: []string{"running", "blocked"}, To: "cancelled"},
		"Complete": {From: []string{"running"}, To: "completed"},
		"Fail":     {From: []string{"running"}, To: "failed"},
		"Unblock":  {From: []string{"blocked"}, To: "running"},
	},
}
